from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from io import BytesIO
from datetime import date
from django.conf import settings
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase import cidfonts
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase.pdfmetrics import registerFont

# Register a font that supports ₹ symbol, like DejaVuSans
import os
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont

# Adjust path based on where you saved the font
# font_path = os.path.join(settings.BASE_DIR, 'static', 'fonts', 'DejaVuSans.ttf')
#
# pdfmetrics.registerFont(TTFont('DejaVuSans', font_path))

FONT_PATH = os.path.join("static", "fonts", "DejaVuSans.ttf")
pdfmetrics.registerFont(TTFont("DejaVuSans", FONT_PATH))



def generate_single_receipt(payment):
    buffer = BytesIO()
    p = canvas.Canvas(buffer, pagesize=A4)

    # Set title and starting Y position
    p.setFont("Helvetica-Bold", 18)
    p.drawString(200, 800, "Payment Receipt")

    # Basic details
    p.setFont("Helvetica", 12)
    y = 760
    line_height = 20

    p.setFont("DejaVuSans", 12)

    p.drawString(100, y, f"Receipt No: {payment.receipt_number}"); y -= line_height
    p.drawString(100, y, f"Owner Name: {payment.house.owner_name}"); y -= line_height
    p.drawString(100, y, f"House Number: {payment.house.house_number}"); y -= line_height
    p.drawString(100, y, f"Fee Type: {payment.fee_type.name}"); y -= line_height
    p.drawString(100, y, f"Amount Paid: ₹{payment.amount}"); y -= line_height
    p.drawString(100, y, f"Paid On: {payment.paid_on}"); y -= line_height
    p.drawString(100, y, "Thank you for your payment!")

    # Footer

    p.setFont("Helvetica-Oblique", 10)
    p.drawString(100, 80, f"Generated by {payment.house.association.name} Management System")

    p.showPage()
    p.save()

    return buffer.getvalue()



def generate_advance_receipt(house, fee, month_list_str, year, total_amount, receipt_number):
    buffer = BytesIO()
    p = canvas.Canvas(buffer, pagesize=A4)

    # Header
    p.setFont("Helvetica-Bold", 18)
    p.drawString(180, 800, "Advance Payment Receipt")

    # Body content
    p.setFont("Helvetica", 12)
    y = 760
    line_height = 20

    p.setFont("DejaVuSans", 12)
    p.drawString(100, y, f"Receipt No: {receipt_number}"); y -= line_height
    p.drawString(100, y, f"Owner Name: {house.owner_name}"); y -= line_height
    p.drawString(100, y, f"House Number: {house.house_number}"); y -= line_height
    p.drawString(100, y, f"Fee Type: {fee.name}"); y -= line_height
    p.drawString(100, y, f"Paid Months: {month_list_str} {year}"); y -= line_height
    p.drawString(100, y, f"Total Amount Paid: ₹{total_amount}") ; y -= line_height
    p.drawString(100, y, f"Paid On: {date.today().strftime('%Y-%m-%d')}"); y -= line_height

    p.drawString(100, y - 10, "Thank you for your payment!")

    p.setFont("Helvetica-Oblique", 10)
    p.drawString(100, 80, f"Generated by {house.association.name} Management System")

    p.showPage()
    p.save()
    return buffer.getvalue()

def generate_single_receipt_corpus(house, amount, receipt_no):
    buffer = BytesIO()
    p = canvas.Canvas(buffer, pagesize=A4)

    p.setFont("Helvetica-Bold", 18)
    p.drawString(200, 800, "One-Time Joining Fee Receipt")

    y = 760
    line_height = 20
    p.setFont("DejaVuSans", 12)

    p.drawString(100, y, f"Receipt No: {receipt_no}"); y -= line_height
    p.drawString(100, y, f"Owner Name: {house.owner_name}"); y -= line_height
    p.drawString(100, y, f"House Number: {house.house_number}"); y -= line_height
    p.drawString(100, y, f"Amount Paid: ₹{amount}"); y -= line_height
    p.drawString(100, y, f"Paid On: {date.today().strftime('%Y-%m-%d')}"); y -= line_height
    p.drawString(100, y, "Thank you for becoming a member!")

    p.setFont("Helvetica-Oblique", 10)
    p.drawString(100, 80, f"Generated by {house.association.name} Management System")

    p.showPage()
    p.save()
    return buffer.getvalue()
