# Generated by Django 5.2.4 on 2025-07-23 18:10

import django.db.models.deletion
import houses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('associations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=100)),
                ('house_number', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('membership_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('membership_date', models.DateField(default=houses.models.current_date)),
                ('active', models.BooleanField(default=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('corpus_fund_paid', models.BooleanField(default=False, help_text='Check if corpus fund has been paid')),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='associations.association')),
            ],
        ),
    ]
