# Generated by Django 5.2.4 on 2025-07-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colonybilling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associationfeetype',
            name='frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=20),
        ),
    ]
